default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost


development:
  <<: *default
  database: soukai_dev
  username: test
  password: denx233*CHAN

test:
  <<: *default
  database: soukai_dev
  username: test
  password: denx233*CHAN

production:
  <<: *default
  database: soukai
  username: test
  password: denx233*CHAN


